### ISSUE TITLE
Improve code coverage upto 90%

### ISSUE THREAD

**Issue by r0h4n** [Tendrl/gluster_bridge#4]
We need to collectively start improving the unit test code coverage for this project.

Current coverage: https://coveralls.io/github/Tendrl/gluster_bridge

Unit tests framework: http://doc.pytest.org/en/latest/

How to write unit tests: http://docs.openstack.org/developer/horizon/topics/testing.html

Contribute patches here: https://github.com/Tendrl/gluster_bridge/tree/master/gluster_bridge/tests

Lets work on this issue together to get code coverage up to 90%, please share doubts/inputs on this issue itself

**Comment by alfredodeza** [comment]
Is it a requirement to use `oslotest`? Or is it linked here as a reference?

**Comment by r0h4n** [comment]
It's a requirement. Oslo libraries help speed development

**Comment by alfredodeza** [comment]
@r0h4n would you mind explaining a bit how does it help? I see it has some utilities, but *I* see it as a barrier for contribution on writing unit tests.  In the Ceph org. most projects use `py.test` (the test runner) and end up using some of its utilities as well.

The end result is that there is no need to learn a new framework (there is no requirement to use anything it provides), it removes Python's requirement to inherit from a base `TestCase` class, allows to use plains `assert` statements which come already with deep comparisons on error.

Using plain asserts is a massive improvement because no one is required to remember these:

    self.assertEqual(a, b)
    self.assertNotEqual(a, b)
    self.assertTrue(x)
    self.assertFalse(x)
    self.assertIs(a, b)
    self.assertIsNot(a, b)
    self.assertIsNone(x)
    self.assertIsNotNone(x)
    self.assertIn(a, b)
    self.assertNotIn(a, b)
    self.assertIsInstance(a, b)
    self.assertNotIsInstance(a, b)
    self.assertRaises(exc, fun, *args, **kwds)
    self.assertRaisesRegex(exc, r, fun, *args, **kwds)
    self.assertWarns(warn, fun, *args, **kwds)
    self.assertWarnsRegex(warn, r, fun, *args, **kwds)
    self.assertLogs(logger, level)
    self.assertMultiLineEqual(a, b)
    self.assertSequenceEqual(a, b)
    self.assertListEqual(a, b)
    self.assertTupleEqual(a, b)
    self.assertSetEqual(a, b)
    self.assertDictEqual(a, b)
    self.assertAlmostEqual(a, b)
    self.assertNotAlmostEqual(a, b)
    self.assertGreater(a, b)
    self.assertGreaterEqual(a, b)
    self.assertLess(a, b)
    self.assertLessEqual(a, b)
    self.assertRegex(s, r)
    self.assertNotRegex(s, r)
    self.assertCountEqual(a, b)

The deep comparison engine it provides works for all data structures, point out at the exact place where the expectation is not met. For example:

    test_assert2.py F
    
    ======= FAILURES ========
    _______ test_set_comparison ________
    
        def test_set_comparison():
            set1 = set("1308")
            set2 = set("8035")
    >       assert set1 == set2
    E       assert {'0', '1', '3', '8'} == {'0', '3', '5', '8'}
    E         Extra items in the left set:
    E         '1'
    E         Extra items in the right set:
    E         '5'
    E         Use -v to get the full diff

So my recommendation to allow easier contributions to unit tests, improve the quality of them by using simple asserts (and optionally all of the utilities provided) is to use a test runner like `py.test`

**Comment by r0h4n** [comment]
If Oslotest might prove as a risk, let us start with py.test and evaluate if we require Oslotest at a later stage.

I am ok with using py.test for writing unit tests

**Comment by mbukatov** [comment]
I would also suggest to start with py.test instead of oslotest (not sure how much a qe team's voice is important here though).

**Comment by r0h4n** [comment]
@nnDarshan @nthomas-redhat  Any updates on this issue? Could send a patch to get this started?

**Comment by GowthamShanmugam** [comment]
Hi Rohan,
         I dont know anything about code flow, and unit testing is also new for me. Can you please conduct any session for me. I have already sent a mail about this on last week. I want help to do this.

**Comment by r0h4n** [comment]
Hey @GowthamShanmugam , Unit testing shouldnt really require a complete understanding of the code. Pick a function to test and write positive and negative unit tests for it

Refer:
http://doc.pytest.org/en/latest/example/
https://wiki.openstack.org/wiki/SmallTestingGuide

**Comment by GowthamShanmugam** [comment]
hi @r0h4n 
    for testing i have imported some package like this (from tendrl.gluster_bridge.log import log), But if i run the code bash run_travis.sh it says importError: No module named tendrl.gluster_bridge.log . what i have to do for this? i have to set any link?

**Comment by GowthamShanmugam** [comment]
@r0h4n 
Any script for run unit test?

**Comment by r0h4n** [comment]
@GowthamShanmugam please file a separate issue for the import error. 

To run unit tests in python 2.7 env:  "tox -e py27"  (check /tox.ini for details)
Tox documentation: https://tox.readthedocs.io/en/latest/

**Comment by GowthamShanmugam** [comment]
hi @r0h4n 
package tendrl.gluster_bridge.common.db.event is imported in many place but i dont see the package common ( tendrl.gluster_bridge.common) anywhere so testing gives exception, where is that common package?

**Comment by GowthamShanmugam** [comment]
Hi @r0h4n ,
        Now i am writing test case for gluster_bridge module persister, the problem is etcdobj is imported every where but it is not in gluster bridge it is moved to bridge_common, So we have to change imports
