### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by GowthamShanmugam** [Tendrl/gluster_bridge#7]
For unit test i have imported a module called Eventer  (from gluster_bridge.manager.eventer import Eventer). When i try to run a test file it says import error like (ImportError: No module named tendrl.gluster_bridge.common.db.event). I dont see any module called Common in gluster_bridge.

**Comment by GowthamShanmugam** [comment]
Any document for how to configure and run this tendrl? Because without  configure properly we don't know exactly which is bug, and how to run unit test properly :)

**Comment by GowthamShanmugam** [comment]
Hi @r0h4n ,
 All imports starts with  tendrl is gives error like(from tendrl.gluster_bridge.log import log)... 

ImportError: No module named tendrl.gluster_bridge.log

**Comment by r0h4n** [comment]
Can you share the patch you have been working on?

**Comment by GowthamShanmugam** [comment]
https://gist.github.com/GowthamShanmugam/668fd16a404f1f323cf8889317351bf1

**Comment by r0h4n** [comment]
Firstly, please use py.test, modify the  gluster_bridge/tests/base.py to use py.test instead of oslotest as discussed in the unit test issue,

I dont see any import error, your patch worked fine
http://paste.openstack.org/show/577218/

what exactly is blocking your patch?

**Comment by r0h4n** [comment]
#12
